# Generated by Django 2.2.6 on 2019-11-22 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20191123_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='phone',
            field=models.CharField(default=0, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number entered must be in a valid format.', regex='^(?:\\s+|)((0|(?:(\\+|)91))(?:\\s|-)*(?:(?:\\d(?:\\s|-)*\\d{9})|(?:\\d{2}(?:\\s|-)*\\d{8})|(?:\\d{3}(?:\\s|-)*\\d{7}))|\\d{10})(?:\\s+|)$')]),
            preserve_default=False,
        ),
    ]
