# Generated by Django 2.2.6 on 2019-11-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20191123_0110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
